version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql
    build:
      context: .
      dockerfile: cmd/server/storage/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./cmd/server/storage:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grpc_service
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:9000" # http
      - "443:443" # https

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080