version: '3'
services:
  db:
    container_name: db
    platform: linux/x86_64
    image: mysql
    hostname: backend-service-db
    build:
      context: .
      dockerfile: backend-service/cmd/server/storage/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./backend-service/cmd/server/storage:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backend_service
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: mysql -h backend-service-db -P 3306 --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      start_period: 10s
      interval: 2s
      timeout: 5s
      retries: 20
  server:
    build:
      context: .
      dockerfile: backend-service/Dockerfile
    hostname: backend-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9090:9090" # http
    volumes:
      - ./app
  api:
    build:
      context: .
      dockerfile: api-service/Dockerfile
    hostname: api-service
    depends_on:
      - server
    ports:
      - "8333:8333" # http
    healthcheck:
      test: curl --fail http://api-service:8333/healthcheck || exit 1;
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080